---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
    - targetPort: 80 # container
      port: 81  # service 
      protocol: TCP