# ServiceAccounts are used with: 👉 IAM Roles for Service Accounts (IRSA)
# Example: Pod needs S3 access
# Instead of storing AWS credentials inside pod: Attach IAM role to ServiceAccount
# Kubernetes + AWS OIDC provides temporary credentials
# Application Pod
#    ↓
# ServiceAccount Attached
#    ↓
# OIDC Trust Relationship
#    ↓
# IAM Role Permission Granted
#    ↓
# Pod accesses S3 / DynamoDB / Other AWS services

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  serviceAccountName: example-service-account
  containers:
  - name: nginx
    image: nginx