# when you create the service account, in backend it will create token(bearer token) which is used by external applications to authenticate kubernetes API
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-service-account