# authorizing the user to cluster scoped resources like nodes, pv
# you can attach clusterrole to namespaced resources like pods, deployements but it will give access to the resources with in all namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-cluster-role
rules:
  - apiGroups: [""]
    verbs: ["get", "list"]
    resources: ["nodes"]