image:
  repository: busybox
  tag: latest
  pullpolicy: IfNotPresent
appMessage: "Shipping Service"

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false