# ❌ Environment variables from ConfigMaps or Secrets CANNOT be updated in a running Pod.
# kubectl create configmap  <configMap-Name> --from-literal=<key>=<value>
# kubectl create configmap  <configMap-Name> --from-file=pathtofile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  username: Admin
  password: "123456"