# kubectl create configmap  <configMap-Name> --from-literal=<key>=<value>
# kubectl create configmap  <configMap-Name> --from-file=pathtofile
# Below is the code get specific value from secret
#  env:
#   - name: username
#     valueFrom:
#       secretKeyRef:
#         name: app-config
#         key: username
# ❌ Environment variables from ConfigMaps or Secrets CANNOT be updated in a running Pod.
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-injecting-to-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: app-secret
      command: ["/bin/sh", "-c"]
      args:
        - echo "Password is $password" && sleep 120
