# liveness probe: Checks if the container is alive.
    #1) If the liveness probe fails, Kubernetes assumes the container is dead or stuck and will restart it.
    #2) It helps recover from crashes or deadlocks automatically.

# Readiness probe: Checks if the container is ready to serve traffic.
    # 1) If the readiness probe fails, Kubernetes will remove the pod from the Service endpoints.
    # 2) The container may be running (alive) but not ready to handle requests yet 

# Ready = Safe to receive traffic
# Running properly = Process is alive

# | Probe     | What it decides                     |
# | --------- | ----------------------------------- |
# | Readiness | Should this pod receive traffic?    |
# | Liveness  | Should this container be restarted? |

# Liveness/Readiness is NOT a one-time check.A continuous health monitor for the running container.It keeps checking for the entire life of the pod
# Liveness checks DB process health by verifying the database port or running a ping command like mysqladmin or pg_isready, and restarts the container if it is unresponsive.
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-probes-example
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    
    # # 1️⃣ Startup Probe (wait until Jenkins fully boots)
    # startupProbe:
    #   httpGet:              
    #     path: /login
    #     port: 8080
    #   failureThreshold: 30
    #   periodSeconds: 10

    # 2️⃣ Readiness Probe (is it ready to accept traffic?)
    readinessProbe:
      tcpSocket:               # we have httpGet, tcpsocket and exec
        port: 80
      initialDelaySeconds: 60
      periodSeconds: 10
      failureThreshold: 3

    # 3️⃣ Liveness Probe (is nginx stuck or dead?)
    livenessProbe:
      httpGet:              # we have httpGet, tcpsocket and exec 
        path: /
        port: 80
      initialDelaySeconds: 180
      periodSeconds: 30
      failureThreshold: 3