---
apiVersion: v1
kind: Pod
metadata:
  name: example-hostpath-volume
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh","-c"]
      args:
        - echo "This is an example for volume" >> /opt/volume.txt
      volumeMounts:
        - mountPath: /opt
          name: example-data-volume

  volumes:
    - name: example-data-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate