---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-pvc-pv-example
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: ebs-pvc
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  volumes:
    - name: ebs-pvc
      persistentVolumeClaim:
        claimName: example-pvc-storage-class