---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa # this name we need to configure in oidc connectors refer terraform_kubernetes_poc\eks\data.tf
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::418272799492:role/ebs-csi-controller