
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-storage-class
spec:
  storageClassName: example-ebs-storage-example
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi