apiVersion: v1
entries:
  payments:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-19T20:41:59.6169615+05:30"
    description: A Helm chart for Kubernetes
    digest: bfdd274dc03c4b5647c6ad44a5595b6c4d3a3d80a1801dda34d2a92357b20fdd
    name: payments
    type: application
    urls:
    - payments-0.1.0.tgz
    version: 0.1.0
  shipping:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-19T20:41:59.6169615+05:30"
    description: A Helm chart for Kubernetes
    digest: 9a5b738ee15033edb729b2981642dab6a0f533ab3e7c2ea5ec718c981b8bab00
    name: shipping
    type: application
    urls:
    - shipping-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-19T20:41:59.6110128+05:30"
