---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller-sa # this name we need to configure in oidc connectors refer 
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::418272799492:role/aws-load-balancer-controller-role